// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8fudufdb81EmsK-XLAuzeTf57b5d9LEA',
    appId: '1:534586490308:web:29f68baab3ff87c93d7891',
    messagingSenderId: '534586490308',
    projectId: 'snapmugflutter',
    authDomain: 'snapmugflutter.firebaseapp.com',
    databaseURL: 'https://snapmugflutter-default-rtdb.firebaseio.com',
    storageBucket: 'snapmugflutter.appspot.com',
    measurementId: 'G-GHEF28C33X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhK5vHpxzCh_jgP7sfuWMabS77lS7SFVs',
    appId: '1:534586490308:android:21e8919ca1c3dbf03d7891',
    messagingSenderId: '534586490308',
    projectId: 'snapmugflutter',
    databaseURL: 'https://snapmugflutter-default-rtdb.firebaseio.com',
    storageBucket: 'snapmugflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMI9L_3oFY13wPgHY7-nhZ7TXrZDpuBVQ',
    appId: '1:534586490308:ios:0cfb28429ff2eafb3d7891',
    messagingSenderId: '534586490308',
    projectId: 'snapmugflutter',
    databaseURL: 'https://snapmugflutter-default-rtdb.firebaseio.com',
    storageBucket: 'snapmugflutter.appspot.com',
    androidClientId: '534586490308-5klhe53qknd88mf2s3earqhuh7jvonkg.apps.googleusercontent.com',
    iosClientId: '534586490308-jb2pft666uchuq88ggojcqklih03kv9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapmugForAdmins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMI9L_3oFY13wPgHY7-nhZ7TXrZDpuBVQ',
    appId: '1:534586490308:ios:0cfb28429ff2eafb3d7891',
    messagingSenderId: '534586490308',
    projectId: 'snapmugflutter',
    databaseURL: 'https://snapmugflutter-default-rtdb.firebaseio.com',
    storageBucket: 'snapmugflutter.appspot.com',
    androidClientId: '534586490308-5klhe53qknd88mf2s3earqhuh7jvonkg.apps.googleusercontent.com',
    iosClientId: '534586490308-jb2pft666uchuq88ggojcqklih03kv9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapmugForAdmins',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8fudufdb81EmsK-XLAuzeTf57b5d9LEA',
    appId: '1:534586490308:web:34855af66e8f09953d7891',
    messagingSenderId: '534586490308',
    projectId: 'snapmugflutter',
    authDomain: 'snapmugflutter.firebaseapp.com',
    databaseURL: 'https://snapmugflutter-default-rtdb.firebaseio.com',
    storageBucket: 'snapmugflutter.appspot.com',
    measurementId: 'G-45DKZST0LV',
  );

}